name: dalini_aqsa
description: دليني الأقصى - خدمات منزلية بلمسة واحدة
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  google_fonts: ^6.2.1
  flutter_local_notifications: ^18.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  flutter_secure_storage: ^9.2.4
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
  adaptive_icon_background: "#1B3A5C"
  adaptive_icon_foreground: "assets/icon.png"
  remove_alpha_ios: true
