name: dalini_aqsa
description: دليني الأقصى - خدمات منزلية بلمسة واحدة
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  flutter_secure_storage: ^9.2.4

flutter:
  uses-material-design: true
